package apigen

import (
	"context"

	"github.com/spf13/cobra"
	"github.com/tsaikd/KDGoLib/cliutil/cobrather"
	"github.com/tsaikd/full-stack-demo/cmd"
	"github.com/tsaikd/full-stack-demo/server/applog"
)

// command line flags
var (
	flagType = &cobrather.BoolFlag{
		Name:  "type",
		Usage: "Output types struct",
	}
	flagResource = &cobrather.StringFlag{
		Name:  "resource",
		Usage: "Resource in RAML",
	}
	flagOutput = &cobrather.StringFlag{
		Name:    "output",
		Default: "autogenerated.go",
		Usage:   "Output file of generated package",
	}
)

// Module info
var Module = &cobrather.Module{
	Use:   "apigen",
	Short: "Generate API golang package",
	Dependencies: []*cobrather.Module{
		applog.Module,
		cmd.Module,
	},
	Flags: []cobrather.Flag{
		flagType,
		flagResource,
		flagOutput,
	},
	RunE: func(ctx context.Context, cmd *cobra.Command, args []string) error {
		return nil
	},
}
