package modimport

import (
	"context"

	"github.com/spf13/cobra"
	"github.com/tsaikd/KDGoLib/cliutil/cobrather"
	"github.com/tsaikd/full-stack-demo/cmd"
)

// command line flags
var (
	flagPackage = &cobrather.StringFlag{
		Name:    "package",
		Default: "apiModule",
		Usage:   "golang package name",
	}
	flagDir = &cobrather.StringFlag{
		Name:  "dir",
		Usage: "package directory",
	}
	flagOutput = &cobrather.StringFlag{
		Name:    "output",
		Default: "autogenerated.go",
		Usage:   "Output file of generated package",
	}
)

// Module info
var Module = &cobrather.Module{
	Use:   "modimport",
	Short: "Generate module imports golang package",
	Dependencies: []*cobrather.Module{
		cmd.Module,
	},
	Flags: []cobrather.Flag{
		flagPackage,
		flagDir,
		flagOutput,
	},
	RunE: func(ctx context.Context, cmd *cobra.Command, args []string) error {
		return nil
	},
}
