types:
  Time:
    description: timestamp string
    (GoType):    time.Time
    type:        string
    examples:
      example1: 2016-06-27T06:47:32.652841+00:00
      example2: 2015-08-05T01:47:08.92511+00:00
